### ISSUE TITLE
Failed to run second fab3

### ISSUE THREAD

**Issue by sara-rouhani** [IBM/loyalty-points-evm-fabric#3]
When I want to run the second fab3 after setting environment variables for the second proxy and then runing the fab3 I get the following error. 

Failed to create Fabric SDK Client: failed to initialize configuration: unable to load config backend: loading config file failed: open /home/.../go/src/github.com/hyperledger/fabric-chaincode-evm/examples/first-network-sdk-config-org2.yaml: no such file or directory

I checked the examples directory it only includes EVM_Smart_Contracts.md and  first-network-sdk-config.yaml files.

**Comment by raheelzubairy** [comment]
@sara-rouhani it should be _first-network-sdk-config.yaml_
Thanks!

**Comment by billsklee** [comment]
I am having the same issue.
./fab3
Failed to create Fabric SDK Client: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend: network configuration load failed: failed to load channel configs: failed to load network TLSConfig: failed to load orderer/peer TLSConfig : failed to load orderer cert: failed to load pem bytes from path /opt/gopath/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem: open /opt/gopath/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem: no such file or directory
root@864ad48d0ef1:/opt/gopath/src/github.com/hyperledger/fabric-chaincode-evm# 

Can you please help me to sort out the error?
