### ISSUE TITLE
Failed to create Fabric SDK Client: failed to initialize configuration

### ISSUE THREAD

**Issue by engiwip** [IBM/loyalty-points-evm-fabric#7]
export variables OK
`
export FABPROXY_CONFIG=${GOPATH}/src/github.com/hyperledger/fabric-chaincode-evm/examples/first-network-sdk-config.yaml 
export FABPROXY_USER=User1
root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric/peer# export FABPROXY_ORG=Org1
root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric/peer# export FABPROXY_CHANNEL=mychannel
root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric/peer# export FABPROXY_CCID=evmcc
root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric/peer# export PORT=5000
`
build OK 

root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric/peer#
 `cd $GOPATH/src/github.com/hyperledger/fabric-chaincode-evm/`
root@6985ac657a8b:/opt/gopath/src/github.com/hyperledger/fabric-chaincode-evm#
` go build -o fab3 ./fabproxy/cmd`

run  `./fab3` failed.

result 👎 
**Failed to create Fabric SDK Client: failed to initialize configuration: unable to load endpoint config: failed to initialize endpoint config from config backend:** 
network configuration load failed: failed to load channel configs: failed to load network TLSConfig: failed to load orderer/peer TLSConfig : failed to load orderer cert: failed to load pem bytes from path /opt/gopath/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem: open /opt/gopath/src/github.com/hyperledger/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem: no such file or directory

Bust...
any ideas ? export = $HOME/go may be ...

many thanks.

**Comment by raheelzubairy** [comment]
@engiwip Run these commands (https://github.com/IBM/loyalty-points-evm-fabric#2-setup-fab3) in a new terminal.  These should not be running in the cli container

**Comment by raheelzubairy** [comment]
Updated instructions here: https://github.com/IBM/loyalty-points-evm-fabric/commit/4725c2233db0e6a47baccdac6fb4a392e596910d
